import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import NextAuthProvider from '@/providers/auth-provider'
import { ThemeProvider } from '@/components/theme-provider'
import DesignerContextProvider from '@/components/context/designer'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app',
}

export default function RootLayout({ children }: { children: React.ReactNode }) {
	return (
		<html lang='en'>
			<body className={inter.className}>
				<NextAuthProvider>
					<ThemeProvider
						attribute='class'
						defaultTheme='system'
						enableSystem
						disableTransitionOnChange
					>
						<DesignerContextProvider>{children}</DesignerContextProvider>
					</ThemeProvider>
				</NextAuthProvider>
			</body>
		</html>
	)
}
